stages:
  - test
  - build
  - deploy

variables:
  FRONTEND_DIR: frontend
  BACKEND_DIR: backend

default:
  tags:
    - shell
  before_script:
    - echo "Running on local runner"

build:
  stage: build
  script:
    - docker compose -f docker-compose.yml build

deploy:
  stage: deploy
  script:
    - docker compose -f docker-compose.yml down
    - docker compose -f docker-compose.yml up -d --build